### ISSUE TITLE
werkzeug has lost debug/shared folders in conda packages between 0.11.8 and 0.11.9

### ISSUE THREAD

**Issue by rs2** [conda-forge/werkzeug-feedstock#2]
Using `conda install`.

Compare https://repo.continuum.io/pkgs/free/win-32/werkzeug-0.11.8-py35_0.tar.bz2
to https://repo.continuum.io/pkgs/free/win-32/werkzeug-0.11.9-py35_0.tar.bz2

Side effect: unable to debug `flask` apps using 0.11.9 or newer.

I'm able to create a valid `conda` package locally.

**Comment by mathieu1** [comment]
Cross-post of https://github.com/ContinuumIO/anaconda-issues/issues/1252. Can be closed.

**Comment by rs2** [comment]
Fixed upstream: https://github.com/pallets/werkzeug/issues/1040
